
clc,clear
cnt=0;
for x=0:12
    
str1 = strcat('G:\project_reference\digit dataset\Sample',num2str(x));
if x==3
    z=178;
else
    z = 253;
end
for n=1:z
  str = strcat(str1,'\img (');
    str = strcat(str,num2str(n));
    str = strcat(str,').png');
    
    imgBW = imread(str);
     imgBW = imgBW > 0.2;
%     fid = fopen('datasetlib2.txt', 'at');
% 
%         % (3b) Write vector value to file    
%         % 64-vector is generated by dividing 32x32 image into 64 4x4 regions
%         % Top row is region 1 2 3 4 5 6 7 8.  Second row is 9 ... 16 and so on
%         fprintf(fid, '%i ',x);
%         cnt=cnt+1;
%         for row = 0:31
%             for col = 0:31
%                 fprintf(fid, '%i:%i ',row*32+col+1, imgBW(int8(row+1),int8(col+1))); 
%             end
%         end
%         fprintf(fid, '\n');
%         fclose(fid);
fid = fopen('dataset4.csv', 'at');

for row = 0:31
                    for col = 0:31
                        fprintf(fid, '%i',imgBW(int8(row+1),int8(col+1))); 
                         %if~(row==31 && col==31)
                            fprintf(fid, ', ');
                         %end
                    end
                end
                fprintf(fid, '%i ',x);
                fprintf(fid, '\n');
                fclose(fid);
                
                 fid = fopen('featurevector.csv', 'at');
                
                % (3b) Write vector value to file    
                % 64-vector is generated by dividing 32x32 image into 64 4x4 regions
                % Top row is region 1 2 3 4 5 6 7 8.  Second row is 9 ... 16 and so on
                %fprintf(fid, '- ');
                
%                 for row = 0:7
%                     for col = 0:7
%                         
%                         fprintf(fid, '0,');
%                     end
%                 end
                
                for row = 0:7
                    for col = 0:7
                        fprintf(fid, '%i', sum(sum(imgBW(4*row+1:4*row+4,4*col+1:4*col+4)))); 
                        %if~(row==7 && col==7)
                            fprintf(fid, ', ');
                         %end
                    end
                end
                fprintf(fid, '%i ',x);
                fprintf(fid, '\n');
                fclose(fid);
    
    
    end
    
    
end
 cnt
    