
clc,clear
for x=0:12
str = strcat('G:\project_reference\digit dataset\Sample');
if x==3
    z=180;
else
    z = 280;
end
for n=1:z
    str = strcat('img',num2str(n));
    str = strcat(str,'.png');
    
    fid = fopen('datasetlib2.txt', 'at');

        % (3b) Write vector value to file    
        % 64-vector is generated by dividing 32x32 image into 64 4x4 regions
        % Top row is region 1 2 3 4 5 6 7 8.  Second row is 9 ... 16 and so on
        fprintf(fid, '%i ',x);
        
        for row = 0:31
            for col = 0:31
                fprintf(fid, '%i:%i ',row*32+col+1, imgBW(int8(row+1),int8(col+1))); 
            end
        end
        fprintf(fid, '\n');
        fclose(fid);
fid = fopen('dataset4.csv', 'at');

for row = 0:31
                    for col = 0:31
                        fprintf(fid, '%i',imgBW(int8(row+1),int8(col+1))); 
%                         if(~(row==7 && col==7))
                            fprintf(fid, ', ');
%                         end
                    end
                end
                fprintf(fid, '%i ',x);
                fprintf(fid, '\n');
                fclose(fid);
    
    end
    
    
 end
    