 fid = fopen('featurevector.csv', 'w');
 for row = 0:31
                    for col = 0:31
                        fprintf(fid, '0');
                        
                        if ~(row==31 && col==31)
                        fprintf(fid, ', ');
                        end
                    end
 end
                fprintf(fid, '\n');
for n=1:9  
str = strcat('image',num2str(n));
    str = strcat(str,'.jpg');
    my_image = imread(str);
    %my_image = im2double(my_image);
    imgBW = my_image;
    
    imgBW=imgBW>0.2;
    
   
                
                % (3b) Write vector value to file    
                % 64-vector is generated by dividing 32x32 image into 64 4x4 regions
                % Top row is region 1 2 3 4 5 6 7 8.  Second row is 9 ... 16 and so on
                %fprintf(fid, '- ');
                
                
                 
              for row = 0:31
                    for col = 0:31
                        
                        fprintf(fid,'%i', imgBW(int8(row)+1,int8(col)+1)); 
                         if~(row==31 && col==31)
                            fprintf(fid, ', ');
                         end
                    end
                end
                %fprintf(fid,'%i',x);
                fprintf(fid, '\n');
                
    
end  
             
    fclose(fid);
                
    
      
    